name = "aoc2025"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
file_streams = ">= 1.7.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
